### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by amuagarwal** [Apollo199999999/LauncherX#1]
Its really good to have the get the launcher working as portable with relative paths for adding the folder or file.

Thanks in Advance

**Comment by Apollo199999999** [comment]
Hm, I will see what I can do.

**Comment by Apollo199999999** [comment]
After further consideration, it is quite difficult to get LauncherX to work as a portable application, simply because it is meant to function as a permanent app launcher on your computer, hence it stores user settings and data in the user's AppData folders, and also uses the absolute paths of the different files/folders. 

Trying to implement LauncherX to function as both a permanent install and a portable app will be very complicated. 

Therefore, this will not be implemented in the near future, unless there is further demand for it.
